### ISSUE TITLE
Font color too bright with Atom Light theme

### ISSUE THREAD

**Issue by MDM23** [jakesankey/git-tab-status#11]
Hi,
I am using your plugin with Atom on Ubuntu. First of all, thanks for your great work! :thumbsup: I recently switched my theme to Atom Light and noticed that the colors are a little bit too bright:

![atom_git-tab-status_colors](https://cloud.githubusercontent.com/assets/10290864/7246566/93539092-e7ff-11e4-8b20-9236241265fb.png)

**Comment by jakesankey** [comment]
Thanks for the feedback.. version 1.9.0 should resolve this issue.
