### ISSUE TITLE
Should use the GitRepository.onDidChangeStatuses event to be notified of changes instead of polling

### ISSUE THREAD

**Issue by lee-dohm** [jakesankey/git-tab-status#12]
In `GitTabStatus._setupWatchConditions()` you start a polling process to execute every half-second to check for updates. It would be, in my opinion, better if you used the [`GitRepository.onDidChangeStatuses`](https://atom.io/docs/api/latest/GitRepository#instance-onDidChangeStatuses) event to be notified when anything changes. This way you aren't polling for no changes, which is most likely the common case. Additionally, the tabs' status should be updated at the same time as the tree view and gutter information ... creating a more unified experience :grinning:

Ref atom/atom#6561

**Comment by jakesankey** [comment]
I agree with you. The interval is a temporary solution. This project previously has used events to determine status, however, those events have historically not been reliable enough in previous betas and caused odd results.. I'll take a look again and see if it has improved. 

Jake
