### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by conormce** [jakesankey/git-tab-status#19]
I've been having crazy memory leaks on OS X (in both Mavericks to El Capitain), by crazy I mean increasing memory usage up to 22GBs in the maximum case. This is solved by restarting atom. I disabled all community packages and gone through them one by one, all others I've tested were fine until I enabled this one. Memory usage doubled within 5 minutes (from 280MBs to 520MBs).

**Comment by jakesankey** [comment]
Please see the readme. This package is now deprecated as the functionality he been merged into atom core. You can uninstall this package and enable the same functionality in the settings for the core "tabs" package. 

Thanks. 

Jake

**Comment by conormce** [comment]
Thanks Jake, that's perfect.
